server:
  port: 8070

eureka:
  client:
    registerWith-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
    
spring:
  cloud:
    config:
      uri:
      - http://${CONFIG_SERVER:localhost}:8888/

feign:
#  hystrix:
#    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
logging:
  level:
    com:
      logixal: debug
      
management:
  endpoints:
    web:
      exposure:
        include: "*"