version: '3.7'
services:
  todo-web-application:
    image: prassyk/theater-service:0.0.1-SNAPSHOT
    container_name: theater-service
    ports:
      - "8085:8085"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: theater
      RDS_USERNAME: theater
      RDS_PASSWORD: dummytheater
    networks:
      - theater-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword 
      MYSQL_USER: theater
      MYSQL_PASSWORD: dummytheater
      MYSQL_DATABASE: theater
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - theater-network  
  
# Volumes
#volumes:
#  mysql-database-data-volume:
volumes:
  mysql-database-data-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:/voldata'  

networks:
  theater-network: